apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
data:
  DISCORD_BOT_ID: {{ .Values.bot_id | b64enc }}
  DISCORD_BOT_NAME: {{ .Values.bot_name | b64enc }}
  DISCORD_BOT_PREFIX: {{ .Values.bot_prefix | b64enc }}
  DISCORD_BOT_TOKEN: {{ .Values.bot_token | b64enc }}
  YANDEX_LOGIN: {{ .Values.yandex_login | b64enc }}
  YANDEX_PASSWORD: {{ .Values.yandex_password | b64enc }}
